// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"
)

type Item struct {
	ID        int32     `json:"id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	Completed bool      `json:"completed"`
}
