// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, title string) (Item, error)
	GetItem(ctx context.Context, id int32) (Item, error)
	ListItems(ctx context.Context) ([]Item, error)
}

var _ Querier = (*Queries)(nil)
